sudo: false

language: ruby

rvm:
  - 2.3.4

cache: bundler
script: bundle exec middleman build

before_deploy: bundle install

deploy: 
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: prod
